version: "3.8"
services:
  frontend:
    image: ayush1041998/reactapp:latest # Use the image from Docker Hub
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: ayush1041998/flaskapp:latest # Use the image from Docker Hub
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    image: mysql:latest # Use the official MySQL image that supports multiple architectures
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: energy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

volumes:
  db_data:
